### ISSUE TITLE
Using full Node scripts (Noob)

### ISSUE THREAD

**Issue by atcwells** [audreyt/node-webworker-threads#102]
Hi there,

I'm trying to 'require' a script within a WebWorker, and getting stuck. I think I understand the basics of why this doesn't work - i.e. that the new thread is not a native NodeJS thread and is instead a thread executing with a plain V8 context, but I'm just trying to confirm my suspicions:

```javascript
            var Worker = require('webworker-threads').Worker;
            var worker = new Worker(function () {
                console.log(1);
                var exec = require('child_process').exec;
                console.log(2);
            });
```

I never get to '2'. I assume this is because the thread is breaking. Is there any native option here?

I think that the only way I'll acheive what I want is to become at least proficient at C++ and muck in, or to ask the Worker thread to start a subset of my main threads abilities and to share space across a data store of some sort, could anyone confirm?

Even then, I'm having problems running a file from my Worker, using 'require' within a second .js file causes the same breaking problem. Is this a continuation of #9?

Thanks,
Alex

**Comment by audreyt** [comment]
Yes, this is the same as #22 (not currently implemented).
