### ISSUE TITLE
Syntax of Threads.create confusing for me

### ISSUE THREAD

**Issue by Cyber1000** [audreyt/node-webworker-threads#104]
Hi,

Sorry I'm a little bit confused by the syntax, maybe because my javascript-skills are not up to date:
From the documentation:
Threads.create().eval(fibo).eval('fibo(35)', cb);

Why do I need to eval two times, once with the function name and once with the complete call, why not something like:
Threads.create().eval(fibo(35), cb)

How would I pass complex objects in there, instead of a number (fibo(data) - 'fibo(35)')

Thanks!

**Comment by audreyt** [comment]
The first time is to inject the `fibo` function into the thread.
To pass a complex object, serialize the object first; using the `Worker` interface the serialization is automatic.
