### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mnahkies** [audreyt/node-webworker-threads#105]
I've been experiencing issues with memory leaks. As far as I can tell I'm not doing anything that should cause memory to be retained, but still see it continuously growing.

I've played around attempting to clean it with the help of the `--expose-gc` flag and explicit calls to `global.gc();` in both the main event loop and in the threads themselves but to no avail.

The memory still seems to remain allocated even if I call destroy on the thread pool, and I see the same results when using a single thread and calling destroy on that.

I've seen the same results on both windows and linux, running node 4. Though linux seemed to leak slower than windows. This has occurred both against the latest release on npm, and a fresh clone of master.

Repro Gist:
https://gist.github.com/mnahkies/174d3aa49d8b03d5198853b4234a8f08

**Comment by vlkv** [comment]
+1

**Comment by mnahkies** [comment]
@vlkv this should be fixed as of v0.7.4, are you still seeing leaks in this version?

**Comment by vlkv** [comment]
I wrote "+1" becase was too happy to see it is fixed in 0.7.4))) At the moment I've updated the library and doing tests. Will report results here...

**Comment by vlkv** [comment]
Hi there!
At the moment we see no memory leaks. But we still watching our service, let it stay up for a week or so))) Thanks!
