### ISSUE TITLE
node-gyp compilation errors

### ISSUE THREAD

**Issue by tasoss** [audreyt/node-webworker-threads#114]
Hello.I would like to ask if this is a known issue
`  \node_modules\webworker-threads\src\bson.cc(868): note: see reference to class template instantiation 'BSONSerializer<CountStream>' being compiled (compiling source file ..\src\WebWorkerThreads.cc)
LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::`vftable'" (__imp_??_7Allocator@ArrayBuffer@v8@@6B@)'; link without /DELAYLOAD:node.exe [node_modules\w ebworker-threads\build\WebWorkerThreads.vcxproj]`

Thanks...

**Comment by TimTinkers** [comment]
I'm getting the same issue trying to install.

**Comment by audreyt** [comment]
Hi! Please give `0.7.6` a try and see if the issue persists? I've rolled the fix from #111 into the release.
