### ISSUE TITLE
Not work wrapped in webworker-threads 

### ISSUE THREAD

**Issue by songbaoqiang** [audreyt/node-webworker-threads#115]
var Worker = require('webworker-threads').Worker;
// var w = new Worker('worker.js'); // Standard API

// You may also pass in a function:
var worker = new Worker(function(){

                    postMessage("I'm working before postMessage('ali').");

                    this.onmessage = function(event) {

                    postMessage("I'm working after postMessage('ali').");

                    var ffmpeg = require('fluent-ffmpeg');
                    var proc = ffmpeg('/Users/vincentsung/Downloads/test/test.mp4')
                    // Base url
                    .addOption('-hls_base_url', 'http://www.ffmlive.com/')
                    // include all the segments in the list
                    .addOption('-hls_list_size',0)
                    .addOption('-hls_segment_filename','out%04d.ts')
                    // setup event handlers
                    .on('progress', function(progress) {

                        var processing_str = 'Processing:' + progress.percent + '% done';
                        console.log(processing_str);
                        })
                    .on('end', function() {
                        console.log('file has been ffmpeg succesfully');
                        })
                    .on('error', function(err) {
                        console.log('an error happened:' + err.message);
                        })
                    // save to file
                    .save('/Users/vincentsung/Downloads/test/out.m3u8');

                        postMessage('Hi ' + event.data);
                        self.close();
                    };
});
worker.onmessage = function(event) {
console.log("Worker said : " + event.data);
};
worker.postMessage('ali');
 @songbaoqiang

**Comment by audreyt** [comment]
Yes. Modules that calls out to the system probably would not work in the worker context. This is specified in our README:

**Note**: If you would like to `require()` native modules in a worker, please consider using the process-based [tiny-worker](https://www.npmjs.com/package/tiny-worker) instead. It does not use threads, but the WebWorker API is compatible.

**Comment by songbaoqiang** [comment]
var Worker = require("tiny-worker");
var worker = new Worker(function () {
                        
                        postMessage("I'm working before postMessage('ali').");
                        
                        self.onmessage = function (ev) {
                        
                        postMessage("I'm working after postMessage('ali').");
                        
                        var ffmpeg = require('fluent-ffmpeg');
                        var proc = ffmpeg('/Users/vincentsung/Downloads/test/test.mp4')
                        // Base url
                        .addOption('-hls_base_url', 'http://www.ffmlive.com/')
                        // include all the segments in the list
                        .addOption('-hls_list_size',0)
                        .addOption('-hls_segment_filename','out%04d.ts')
                        // setup event handlers
                        .on('progress', function(progress) {
                            var processing_str = 'Processing:' + progress.percent + '% done';
                            console.log(processing_str);
                            })
                        .on('end', function() {
                            console.log('file has been ffmpeg succesfully');
                            })
                        .on('error', function(err) {
                            console.log('an error happened:' + err.message);
                            })
                        // save to file
                        .save('/Users/vincentsung/Downloads/test/out.m3u8');
                        
                        postMessage('Hi ' + event.data);
                        };
                        });

worker.onmessage = function (ev) {
    console.log(ev.data);
    worker.terminate();
};

worker.postMessage("Hello World!");


It doesn't work neigther!

**Comment by audreyt** [comment]
Hmm. Please post to the `tiny-worker` issue system here: https://github.com/avoidwork/tiny-worker/issues
