### ISSUE TITLE
thread.destroy()

### ISSUE THREAD

**Issue by minghan** [audreyt/node-webworker-threads#12]
Does thread.destroy() actually destroys the thread? Thanks.

**Comment by guypaskar** [comment]
I am also experiencing something similar. How can I clear all the memory of the thread after thread.eval() ends?

Inside thread.eval I am calling thread.destroy all code was executed.

**Comment by audreyt** [comment]
Hi, a gist or a code snippet will be very helpful here.

(As of 0.7.1 `.destroy()` should destroy the thread immediately with no chance for a leak.)

**Comment by guypaskar** [comment]
It does not update to 0.7.1 when I update via npm. (it updates to 0.6.3)

**Comment by guypaskar** [comment]
Ok. did it. I'm now getting the following error 
TypeError: thread.eval(): the receiver must be a thread object at TypeError (native)

My code is something like that
`app.post('/someFunction', function (req, res) {
            authentication.authorise(req, res, function () {

                var t = Threads.create();
                t.eval(someFunction(req, res, t));
            });
    });
`

`doProcess: function (request, response, thread) {
      
            functionA(arg1, function (result, layout) {
                var resObj = {result: result, layout: layout};

                try {
                 
                    response.send(resObj);
                } catch (e) {
                    response.writeHead(500);
                    response.end(e.toString());
                }

                console.log('destorying doProcess thread from do process');
                thread.destroy();

            });
        });

    }`

And it happening only since I have upgraded.

**Comment by guypaskar** [comment]
Ok, i was able to narrow it down to this.
I have a creation of threads inside another threads (and before I call destroy to the parent thread)
It used to work in 0.6.2 and from 0.6.4 it does not work and give the error from above.

What changed?

**Comment by audreyt** [comment]
The change was that `.destroy` now takes effect immediately, instead of waiting for the next available queue. I'm glad that you are able to reproduce it — Please for now version-lock to 0.6.2 and we'll update this ticket for any new findings.

**Comment by guypaskar** [comment]
Are you able to reproduce as well?

**Comment by audreyt** [comment]
I haven't try reproducing yet — would you mind pasting the narrowed-down case here? I can take a look in ~12 hours.

**Comment by guypaskar** [comment]
Sorry I was not available.
I will do it tomorrow (Wednesday).

**Comment by guypaskar** [comment]
It goes something like that
`app.post('/someFunction', function (req, res) {
    authentication.authorise(req, res, function () {

        var t = Threads.create();
        t.eval(firstFunction(req, res, t));
    });
});

firstFunction = function(req,res, thread) {


    secondFunction(args, function(result){
        var resObj = {result: result};

        try {

            response.send(resObj);
        } catch (e) {
            response.writeHead(500);
            response.end(e.toString());
        }

        console.log('destorying doProcess thread from do process');
        thread.destroy();
    })


};

secondFunction = function(args,callback){
    for(var i = 0 ; i < array.length;  i++){
        //console.log(i);
        var t = Threads.create();
        t.eval(computeFunction(callback,t));
        
    }
};

computeFunction = function(callback,thread){
    //do some calculation
    callback();
    thread.destory();
};
`

**Comment by audreyt** [comment]
I see, so calling `thread.destroy()` from within a thread instead of outside it triggers the error.
Thank you for the reproducible case! I'll look into this during the weekend.

**Comment by guypaskar** [comment]
Awesome. Thanks.

**Comment by guypaskar** [comment]
Anything new with this?

**Comment by guypaskar** [comment]
Nothing???

**Comment by brodybits** [comment]
I suspect the owner is very busy with some things and I am also very busy. I suggest you consider issuing a pull request with a complete, self-contained test case for someone from the community to look at, along with instructions how someone can run it and observe the leak. (The reproducible case that you gave calls some "authentication.authorise" function.)

I added a test-package.js script that is designed to be invoked automatically by npm and will be automatically run by Travis CI. I wonder if you could submit the test case in a similar format.

You may also want to go through the git history of changes between 0.6.2 and 0.6.4 and test them one at a time (perhaps by the classic divide-and-conquer approach) until you see which one actually causes the leak.

**Comment by audreyt** [comment]
Thank you for the patience with the late reply. I was having quite some difficulty with the sample code. 

In this line:

` t.eval(computeFunction(callback,t));`

the `callback` is first called by `computeFunction`, then the thread destroyed, and _then_ the `t.eval()` gets called, by which time the thread no longer exists.

It seems appropriate that this should be an error.

Furthermore, we do not actually support nested thread creation (nor nested workers yet), so it's unlikely that before `0.6.4` the code was functioning as intended.
