### ISSUE TITLE
How should "worker.js" look like?

### ISSUE THREAD

**Issue by bennyn** [audreyt/node-webworker-threads#126]
In your API you specify that you can start a worker like this: 

```javascript
var worker = new Threads.Worker('worker.js');
```

But how should this file (`worker.js`) look like?

I programmed this:

**src/main/js/index.js**

```javascript
var Threads = require('webworker-threads');
var worker = new Threads.Worker('worker.js');
```

**src/main/js/worker.js**

```javascript
module.exports = function () {
  postMessage("I'm working before postMessage('ali').");
  this.onmessage = function (event) {
    postMessage('Hi ' + event.data);
    self.close();
  };
};
```

But I am getting this error:

> Error opening the file worker.js

Can you please help me to go further?

**Comment by audreyt** [comment]
In worker you do not need the `module.exports = function () { } ` wrapper; just the body of the function is sufficient.

The error message means you are running `index.js` from a directory other than `src/main/js/`. Try using an absolute path to make sure it can find `worker.js` ?

**Comment by bennyn** [comment]
@audreyt Thanks for you help! 

It now works. I removed the `module.exports` wrapper and created the thread the following way:

```javascript
var worker = Threads.create();
worker .load(__dirname + '/worker.js');
```

🎈 🎉
