### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by MPeli** [audreyt/node-webworker-threads#134]
Hi,

  I installed following modules

- electron: 1.4.13
- jquery: 3.1.1
- ps-node: 0.1.4
- webworker-threads: 0.7.10

My applications starts. Unfortunately, I see an error in the dev console: 

> .\node_modules\bindings\bindings.js:83 Uncaught Error: Module did not self-register.

- node: v6.9.2
- npm: 4.0.5
- OS: Windows 10

If I remove [js code](https://www.npmjs.com/package/webworker-threads#installing-the-module) related to webworker-threads, the error goes away.

I tried to delete node_modules folder and install all modules again. It did not help. I also tried to build "node-webworker-threads". I carried out following steps:

1. cd .\node_modules\webworker-threads\
2. node-gyp configure --python C:\Python27\python.exe (OK)
3. node-gyp build --python C:\Python27\python.exe (OK)
4. cd ../../
5. npm start 

I did not help either.

I am quite new to nodejs. I might have missed something and did not configure webworker threads properly. I would appreciate any help. 

Thank you, Martin.

There is the complete error:
```
Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (D:\PathToProject\node_modules\bindings\bindings.js:76:44)
```

**Comment by audreyt** [comment]
Hi! Electron has a different build sequence compared to Node when it comes to native modules. Please refer to: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by MPeli** [comment]
Thank you.

I set several environment variables and installed all modules again. It helped. I am able to create a worker in a function [createWindow()](http://electron.atom.io/docs/all/). In the same function I load a URL (index.html). If I try to create a worker in the index.html, the page does not load and I see an error 

> Error opening the file blob:file:///3d8659c7-6feb-4478-a8d4-0cd7cddbafe5

Is it possible to create a worker in index.html? 

Thank you. Martin

Environment variables which I set
```
# Electron's version.
setx npm_config_target 1.4.13
# The architecture of Electron, can be ia32 or x64.
setx npm_config_arch x64
setx npm_config_target_arch x64
# Download headers for Electron.
setx npm_config_disturl https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
setx npm_config_runtime electron
# Tell node-pre-gyp to build module from source code.
setx npm_config_build_from_source true
# Install all dependencies
npm install
```

**Comment by MPeli** [comment]
It seems that there is a conflict between jstree and node-webworkder-thereads. My page index.html loads blank if initialize jstree using [the alternative JSON format](https://www.jstree.com/docs/json/) and if there is this line of code

`var Worker = require('webworker-threads').Worker;`

If I remove the code above or not initialize json tree using json, the page loads ok.
