### ISSUE TITLE
How can I require modules in Worker instances?

### ISSUE THREAD

**Issue by kmod-midori** [audreyt/node-webworker-threads#15]
When I tried to require some native modules in threads like this:

``` javascript
// Generated by CoffeeScript 1.6.2
var assert, equal;

assert = require('assert');

equal = assert.equal;

self.onmessage = function(e) {
  return self.postMessage({
    test: 'QAQ'
  });
};
```

and worker.postMessage doesn't work

``` javascript
// Generated by CoffeeScript 1.6.2
var Worker;

Worker = require('webworker-threads').Worker;

setInterval(function() {
  var worker;

  worker = new Worker('client.js');
  worker.onmessage = function() {//this function has never called since the thread requires modules
    return console.dir(arguments);
  };
  return worker.postMessage({
    foo: 'bar'
  });
}, 1000);
```

**Comment by Decave** [comment]
So just to be clear, even if we use [browserify](http://browserify.org/) to package required modules into something that can be consumed by importScripts, it won't work -- it seems like we can't use modules inside of web workers.

Take the following code:
```
// example_mod.js
var my_mod = require('build/Release/my_module);
```
and say we run `browserify example_mod.js > example_import.js`
If I then have the following:
```
var mod_work = new Threads.Worker(function() {
    function performWork() {
        importScripts('example_import.js');
        return my_mod.run();
    }

   this.onmessage = function(event) {
        postMessage(performWork());
   }
});

mod_work.postMessage();
```

Then the call to `my_mod.run()` hangs indefinitely without being called.

Am I misunderstanding how to use web workers, or can we really not use modules inside of thread workers even if we wrap their code in something that can be called by `importScripts`?

**Comment by audreyt** [comment]
Hmm, this looks legitimate and should work for pure-javascript modules. If I set `example_import.js` to:

```js
var my_mod = {run: function(){ return 123 }}
```

and change the `postMessage(performWork());` line to:

```js
       console.log(performWork());
```

Then I do find it printed out. However if `build/Release/my_module` is a binary module (built by `node-gyp` or similar) then indeed, we have no way of loading them currently.

**Comment by the1mills** [comment]
for the love of all things holy can someone just create "require"
functionality in webworkers?

**Comment by the1mills** [comment]
I dont have the expertise to do this but audrey you probably do or someone
around here does. it would be so frickin' useful to have require abilities
in webworkers.

**Comment by audreyt** [comment]
@the1mills Please consider using https://www.npmjs.com/package/tiny-worker which does support `require` through child processes.
