### ISSUE TITLE
Use Node Module Inside a Pool

### ISSUE THREAD

**Issue by mfigueredo** [audreyt/node-webworker-threads#150]
I guess it is more a question than a issue.
Is there any limitation about use a node module, like[1], inside a pool?

Thanks!

[1]https://github.com/brianc/node-pg-native

**Comment by audreyt** [comment]
This is in our README:

**Note**: If you would like to `require()` native modules in a worker, please consider using the process-based [tiny-worker](https://www.npmjs.com/package/tiny-worker) instead. It does not use threads, but the WebWorker API is compatible.
