### ISSUE TITLE
Why is this a fork instead of a wrapper?

### ISSUE THREAD

**Issue by NodeGuy** [audreyt/node-webworker-threads#151]
I'm trying to understand the relationship between this project and [Threads à gogo](https://github.com/xk/node-threads-a-gogo).  This looks like a fork; why isn't it just a wrapper?

**Comment by audreyt** [comment]
It started as a pull request, which was not merged, and so eventually grew into a fork...

https://github.com/xk/node-threads-a-gogo/pull/28

**Comment by NodeGuy** [comment]
Thank you for the link.
