### ISSUE TITLE
Compilation failure of 0.7.11

### ISSUE THREAD

**Issue by linkmauve** [audreyt/node-webworker-threads#160]
Hello,

I’m trying to install this package on an up to date ArchLinux, using node 8.1.4 and npm 5.3.0, but I get these errors on `npm install`: [webworker-threads.txt](https://github.com/audreyt/node-webworker-threads/files/1149280/webworker-threads.txt)

I suspect the v8 API has changed, if so you’re welcome to change the title of this issue.

I stay available if you need any more information about this issue.

**Comment by linkmauve** [comment]
Current master actually builds, maybe the only thing missing is a release. ^^'

**Comment by audreyt** [comment]
Released as 0.7.12.
