### ISSUE TITLE
WebSql Support?

### ISSUE THREAD

**Issue by namaljayathunga** [audreyt/node-webworker-threads#188]
I am working on an NWJS project. I tried to use WebWorker for sync WebSql. Unfortunately, Chromium has deprecated WebSql support in WebWorkers. Can I use this module to execute WebSql query inside WebWorker? Thanks

**Comment by audreyt** [comment]
This module only executes pure JS code in WebWorker context. It is conceivable that a pure JS SQL engine such as AlaSQL.js will work in Chromium.
