### ISSUE TITLE
thread Pool do not support to run a function with operation buffer?

### ISSUE THREAD

**Issue by chengdonglin** [audreyt/node-webworker-threads#197]
I create a function method which response buffer data, but when I create thread pool to run ,the following err:
Error: ReferenceError: Buffer is not defined

**Comment by audreyt** [comment]
Yes. I would suggest looking into https://www.npmjs.com/package/worker which does work with Buffers. Or the native Node API worker_threads: ttps://nodejs.org/api/worker_threads.html
