### ISSUE TITLE
[Question] How to use nodejs package in child-thread?

### ISSUE THREAD

**Issue by YuzhongHuangCS** [audreyt/node-webworker-threads#33]
I want to parse HTML in child-thread (need jsdom) because it is much slower than the speed fetching web pages, if I parse in main thread, it will fill up the event loop, cause socket timeout and finally ruin the program.

But jsdom is nodejs package, I can't use global variable `jsdom`, or declare new variable `var jsdom = require('jsdom');` as I do in main-thread,
I also try to pass it to child-thread via parameter, just like `worker.postMessage([jsdom, html]);` and of course, failed. Actually I get the jsdom in child-thread. `console.log(event.data[0]);` have some output, but It's not the same with main-thread.

I have a test on serveral nodejs-defined variable, such as `console.log(typeof(require)); console.log(typeof(global));` and I get undefined or very different.

I think the child-thread using a completely different context with main-thread, so is it possible to use nodejs package in child-thread?

Or, what's the right way to do this? (Fork, spawn, cluster? or anything better? These three things will make the program much more complex, and what I want to do is just a simple spider.)

**Comment by sean-hill** [comment]
Could someone post a code sample of how to do this? Everyone is saying use `browserify` in your child thread file, but I'm not sure how to do this. Thanks.

**Comment by rafinskipg** [comment]
Yes @audreyt , i have used browserify, but i 'm not sure how to use the imported file. It returns a function , not my exact code..
