### ISSUE TITLE
Issue installing from npm on Windows 8.1

### ISSUE THREAD

**Issue by weagle08** [audreyt/node-webworker-threads#42]
When installing with npm on Windows 8.1 I get the following error:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v120 to build using the v120 build tools. [S:\dev\nodegyptest\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]

I am not sure how to change the node-gyp build settings so a work around for anyone experiencing this issue follows:
1) Pull the source
2) Navigate a command prompt to the source directory
3) type npm install nan
4) type node-gyp configure
5) type node-gyp build /tv:12.0

Builds without issue for me using this method.
Setup:
Windows 8.1
Visual Studio 2013
Python 2.7.9

**Comment by Oza94** [comment]
Hello,

I think I encounter a related issue. Build fails through npm and when trying to build from sources. What I have tried

```
npm install webworker-threads
npm install webworker-threads --msvs_version=2013
npm install webworker-threads --msvs_version=2013 --build-from-source

# in test a test dir
git clone https://github.com/audreyt/node-webworker-threads.git
cd node-webworker-threads
npm install nan
node-gyp configure
node-gyp build # also tried weagle08's solution without success
```

I've put the [npm output](http://pastebin.com/mu5gtuSc) and the [npm-debug.log](http://pastebin.com/hEiCWpRQ) on pastebin.

My setup

 * Windows 8.1
 * VS 2013
 * Python 2.7

**Comment by audreyt** [comment]
This seems identical to https://github.com/ErikDubbelboer/node-sleep/issues/18#issuecomment-63433409 and seems like a Node/VS2013/Win8 issue.

Would upgrading to Node v0.10.36 help? If not then the workaround of downloading `qos.h` as suggested by the node-sleep issue might be the way to go.
