### ISSUE TITLE
native modules in workers

### ISSUE THREAD

**Issue by Climax777** [audreyt/node-webworker-threads#47]
Hello

This is more of a question than an issue, and may become a feature request.

How can I make use of node modules in workers? Especially node modules that rely on other modules which make use of native C++ code? ex: https://github.com/brianc/node-postgres

Thanks

**Comment by sochka** [comment]
+1

**Comment by audreyt** [comment]
Currently one need to use a process-based web worker implementation, not this one, to make use of native modules.

For plain node modules, one can use `onejs` or `browserify` or `webpack` to turn them into a `importScripts` compatible packed file.
