### ISSUE TITLE
ReferenceError: fibo is not defined

### ISSUE THREAD

**Issue by poliveira89** [audreyt/node-webworker-threads#52]
I have a small file `threads.js` based on this [example]() the content of the file is:
````javascript
var threads = require('webworker-threads'),
    sleep = require('sleep').sleep;

var random = function(low, high) {
    return Math.floor(Math.random() * (high - low + 1) + low);
};
function fibo(n, low, high) {
    var rnd = random(low, high);
    sleep(rnd);
    return n > 1 ? fibo(n - 1) + fibo(n - 2) : 1;
}

var threadOne = threads.create(),
    threadTwo = threads.create(),
    threadThree = threads.create();
threadOne.eval('fibo(10, 60, 120)', function(err, result) {
    if (err) { console.error(err); }

    console.log('[ thread-1 ] result: %s', result);
});
threadTwo.eval('fibo(10, 60, 120)', function(err, result) {
    if (err) { console.error(err); }

    console.log('[ thread-2 ] result: %s', result);
});
threadThree.eval('fibo(10, 60, 120)', function(err, result) {
    if (err) { console.error(err); }

    console.log('[ thread-3 ] result: %s', result);
});
````

When I execute `node threads.js`:
````bash
vagrant@vagrant-ubuntu-trusty-64:~/nodejs$ node threads.js
[Error: ReferenceError: fibo is not defined]
[ thread-2 ] result: null
[Error: ReferenceError: fibo is not defined]
[ thread-3 ] result: null
[Error: ReferenceError: fibo is not defined]
[ thread-1 ] result: null
````

For every thread I receive the error `[Error: ReferenceError: fibo is not defined]` but as we can see I have the function declared as the example and for an experiment, I changed to `var fibo = function(n, low, high) { ... }` still did not worked.

**Comment by lucnap** [comment]
require('sleep') is the problem
You can't require external libraries.
The solution is to put all your functions and external libraries in a file, [browserify](https://github.com/substack/node-browserify) that file and then make a thread.load() of that browserified file.

**Comment by poliveira89** [comment]
I have found that use `require` on the code block that will be loaded on `thread.load` does not work.

But your suggestion with browserify, could be a great tip! Thanks :+1:
