### ISSUE TITLE
Thread function's parameter Object type is impossible?

### ISSUE THREAD

**Issue by JohnJeong123** [audreyt/node-webworker-threads#53]
I have a question about webworker-threads usages

When I use .eval(function) and make function thread

1) function's param object is impossible?

2) callback function is impossible?

**Comment by audreyt** [comment]
1. To pass object arguments, use the WebWorker API, not the `.eval` API. See `test.js` for an example.
2. You can use `.eval(code, callback)` — see `examples/ex01_basic.js` for an example.
