### ISSUE TITLE
Implement onError() callback for Workers

### ISSUE THREAD

**Issue by jolcese** [audreyt/node-webworker-threads#6]
It would be great to have the onError() callback implemented to catch exceptions on the worker.
See http://www.w3.org/TR/workers/#runtime-script-errors

**Comment by Optay** [comment]
I've been poking around for hours trying to find this call buried here, in a closed thread. I have one suggestion and a question:
1. Please add the 'onerror' callback to the readme.
2. A quick googling reveals a couple of stack trace modules (long-stack-traces and node-stack-trace). Can these be used to add debug info to this error callback?
