### ISSUE TITLE
Stopping a worker thread causes cpu 100% and hang

### ISSUE THREAD

**Issue by meepdarknessmeep** [audreyt/node-webworker-threads#62]
Ubuntu 15.04, 64 bit, node v0.12.7

code:
```

                var worker = new Worker(function()
                {
                
                    this.onmessage = function(event)
                    {
                        iscode = event.data[0] === "1";
                        var str = event.data.substring(1);
                        
                        postMessage(JSON.stringify({
                            code: 501,
                        }));
                        
                    }
                    
                });
                
                worker.onmessage = function(event)
                {
                    var json = JSON.parse(event.data);
                    
                    // ...
                    
                    worker.terminate();
                    
                };
                
                worker.postMessage(
                    ((yes ? "1" : "0") + 
                    str
                );
```

**Comment by meepdarknessmeep** [comment]
also a note, it works the first time i create a worker, but after that it just hangs

**Comment by audreyt** [comment]
Does this happen with Node 0.10?

**Comment by Velissel** [comment]
I am having the exactly the same problem, but with this.close() in side a worker. If this.close() is removed, everything works perfectly except I assume worker is repeatedly created and not released at all.

Here is the output of server:
```
worker started
worker finished
POST /util/auto-event-match 200 560.866 ms - 75792

worker started
worker finished
null 296
```
It works fine for first request, it also gives response on second request, however you can see that the second request is never ended and at the same time CPU usage is boosted to 100%, then no further request is accepted.

Am I using worker in a wrong way? Could any one help?

example.js
```
var autoEventMatch = require('auto-event-match');
function (req, res, next) {
	var results = /* an object has baseEventList and targetEventList arrays as attributes */
	autoEventMatch(results.baseEventList, results.targetEventList, function (err, eventPairs) {
		//suppose it will never fail
		res.json(responses.getSuccessResponse(eventPairs));
	});
}
```

auto-event-match.js
```
module.exports = function (baseEventList, targetEventList, fn) {
	var _worker = new worker(function () {
		var self = this;
		self.onmessage = function (e) {
			console.log('worker started');
			var eventPairs = [];
			/* some cpu intensive work */
			self.postMessage(eventPairs);
			self.close();
			console.log('worker finished');
		}
	});
	_worker.onmessage = function (e) {
		fn(e.data);
	}
	_worker.postMessage();
}
```

**Comment by melfardi** [comment]
Same as @Velissel with node `4.2.1` and webworker-threads `0.6.2` with the simple *hello ali example* on an express get query : 

    const Threads = require('webworker-threads');
    const helloJob = require('../../job/hello');

    module.exports.hello = (req, res) => {
      const helloJobWorker = new Threads.Worker(helloJob);
      helloJobWorker.onmessage = function handle(event) {
        helloJobWorker.terminate();
        return res.status(HttpStatus.OK).json({
          message: 'Worker said : ' + event.data
        });
      };
      helloJobWorker.postMessage('ali');
    };

hello.js :

    module.exports = function hello() {
      this.onmessage = function handle(event) {
        postMessage(`Ok ${event.data}`);
      };
    };

**Comment by yufeih** [comment]
Does [this](https://github.com/yufeih/node-webworker-threads/commit/22b91a2a691267e65cebd09c7a04f23b1aba6344) help?

**Comment by audreyt** [comment]
Indeed it helps. Released as part of 0.6.3.

**Comment by WoodySlum** [comment]
Hi,

I have still the issue with the last version.
Node : 6.3.1
node-webworker-threads : master `"webworker-threads": "github:audreyt/node-webworker-threads#master"`
I checked that the fix described above is in package code.
Environment : Mac OS Sierra 10.12.4

When I destroy thread's worker, the node process is taking 100% CPU :

        var worker = new Worker(function(){
          this.onmessage = function(instance) {
            this.postMessage(instance.data);
          };

        });
        worker.onmessage = function(event) {
          console.log(event.data);
        };
        worker.thread.destroy();
        //worker.terminate();
        console.log(worker);

https://www.dropbox.com/s/yw7ghff2kbgu04z/node-webworker-issue.png?dl=0

Same if calling `worker.terminate();`

Any clue ?

**Comment by audreyt** [comment]
The example above worked for me on macOS Sierra 10.12.5 with Node 6.10.3 and Node 8.0.0.
