### ISSUE TITLE
Can I use this module as a sandbox ?

### ISSUE THREAD

**Issue by scaljeri** [audreyt/node-webworker-threads#63]
I was just wondering if I could use this module to run untrusted code in? Because I need to run code that should not access the file-system, internet or any global variables/functions.

**Comment by audreyt** [comment]
`importScript` can load and run arbitrary files from the filesystem, but not write to it.

If you comment out `readFileSync` in src/WebWorkerThreads.cc then I suppose it's an acceptable isolation layer.

**Comment by scaljeri** [comment]
Thanks for the quick response! For me, knowing that writing is not possible is good enough :)
