### ISSUE TITLE
Upgrade to nan 2.x

### ISSUE THREAD

**Issue by jorrit** [audreyt/node-webworker-threads#67]
To support Node.js 4.x.

Also adding to nodejs/node#2798.

**Comment by audreyt** [comment]
Also adding as a prerequisite to #66. Help welcome!

**Comment by marcominetti** [comment]
+1

**Comment by marcominetti** [comment]
Is anyone already working on this issue? @audreyt I can port to nan 2.x and PR if you're busy...

**Comment by audreyt** [comment]
Hi! I'm currently traveling in UK and Ireland (and Paris)... Please do pick this up and work on the nan 2.x port, I'll merge it soon as I got internet :-)

**Comment by heavyk** [comment]
:+1: :)
