### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by brodybits** [audreyt/node-webworker-threads#75]
There seems to be a number of test functions but they do not seem to check results automatically. Perhaps we could use some multi-threading tests from JXCore as a starting point. Unfortunately I am not sure when I will get a chance to work on this.

**Comment by brodybits** [comment]
I just pushed a very simple automatic test suite in #80. I recommend we consider "continuous integration" testing (such as Travis, AppVeyor, etc.) at some point.

**Comment by audreyt** [comment]
Sure! Would you like to commit a `.travis.yml` for example?

**Comment by brodybits** [comment]
See PR #82, testing on all supported versions of Node.js 0.10/0.12/4.0/4.1/4.2 and io.js (3.3.1). See https://travis-ci.org/literunner/node-webworker-threads for sample output. @audreyt in case you haven't used Travis CI before you can sign in using your Github ID and should be able to add the project very easily.

**Comment by audreyt** [comment]
<img src="https://api.travis-ci.org/audreyt/node-webworker-threads.svg" />
:rainbow: 
Thank you so much!

**Comment by brodybits** [comment]
I just fixed the Travis CI link in your `master` branch. Thanks for integrating!
