### ISSUE TITLE
`nan` seems to crash `npm install webworker-threads`

### ISSUE THREAD

**Issue by andywer** [audreyt/node-webworker-threads#83]
Dependency `nan` seems to crash `npm install webworker-threads` with Node 4.x:
https://travis-ci.org/andywer/threadpool-js/jobs/88154052

Any ideas?

**Comment by audreyt** [comment]
`../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`

Try this?

https://github.com/audreyt/node-webworker-threads/blob/master/.travis.yml#L13

**Comment by andywer** [comment]
Works. Thank you!
