### ISSUE TITLE
print no message when exception 

### ISSUE THREAD

**Issue by yinrong** [audreyt/node-webworker-threads#84]
In thread, if an exception happens, there is no message printed, which makes debugging very hard.

**Comment by audreyt** [comment]
Hi! Did you add an `onerror` handler?
Please see https://github.com/audreyt/node-webworker-threads/blob/master/test.ls#L14 ( JS: https://github.com/audreyt/node-webworker-threads/blob/master/test.js#L29 ) for an example.
