### ISSUE TITLE
Handle traffic with Workers and `ws` library?

### ISSUE THREAD

**Issue by SzAmmi** [audreyt/node-webworker-threads#89]
Is is possible? Any example?

**Comment by audreyt** [comment]
Not easily because currently we cannot do a native `require` with binary modules from within a worker — mostly people use Worker for CPU intensive processing, not network bound processing.

For full-fledged thread-based workers please consider an alternate runtime such as https://github.com/jxcore/jxcore (note I have not used it myself :-))

Thanks for the question1

**Comment by SzAmmi** [comment]
So, I can't import any additional module in worker file?

**Comment by audreyt** [comment]
You can — as long as they are pure JavaScript — with `importScripts`, and there are ways to package multiple such modules into one script such as `requirejs` or maybe `webpack`. Please see https://github.com/audreyt/node-webworker-threads/issues/81#issuecomment-147893459

**Comment by SzAmmi** [comment]
I have to do:

<code>var WebSocket = importScript("./node_modules/ws/lib/WebSocket.js");
var WebSocketServer = WebSocket.Server;
</code>

or:
<code>importScript("./node_modules/ws/lib/WebSocket.js");
var WebSocketServer = WebSocket.Server;</code>

or I can't?

**Comment by SzAmmi** [comment]
Oh, it must be pure JavaScript. Hmm... can I do:

```javascript
var WebSocket = require('ws');
var Worker = require('webworker-threads');
worker = new Worker(function(ws){ /* code with ws here */ }, WebSocket)

**Comment by audreyt** [comment]
Unfortunately one can also only pass json (well bson) serializable objects
into a worker and from messages sent from a worker, so socket handles
probably would not work either.

SzAmmi <notifications@github.com> 於 2015年12月11日週五 22:59 寫道：

**Comment by SzAmmi** [comment]
Found some code: https://nodejs.org/dist/latest-v5.x/docs/api/cluster.html#cluster_class_worker

I can do:

```javascript
var cluster = require('cluster');

if (cluster.isMaster) {
	var worker = cluster.fork();
	worker.send("Hi there!");
} else if (cluster.isWorker) {
	process.on('message', function(msg) {
		console.log("Got message:" + msg);
	});
}
