### ISSUE TITLE
writing to file

### ISSUE THREAD

**Issue by 0x1mason** [audreyt/node-webworker-threads#90]
I'm considering contributing a `writeFileSync_`. However, I wanted to check if there's a technical reason you haven't already implemented it, eg a sandbox or what what.

**Comment by audreyt** [comment]
There is an old (abandoned) spec:

https://developer.mozilla.org/zh-TW/docs/Web/API/LocalFileSystemSync

http://www.html5rocks.com/en/tutorials/file/filesystem-sync/

Still it's OK to implement the underlying primitives, then perhaps exposed under a flag to `require`.

**Comment by 0x1mason** [comment]
I'll take a look at it. I may hold off and see what kind of interest there is in my module and how it fares in actual usage.

https://github.com/0x1mason/async-console-log

Thanks for maintaining this. It opens up lots of very cool possibilities.
