### ISSUE TITLE
importScripts example on Node.js server

### ISSUE THREAD

**Issue by ORESoftware** [audreyt/node-webworker-threads#92]
Can the readme for this module provide a quick example of using importScripts with NPM modules and how path issues are resolved?

For example, for underscore, we might do with require()
```js
var _ = require('underscore');
```
but with importScripts, is it
```js
var _ = importScripts('underscore'); // ?
```
surely not..

furthermore, with libraries like ```Cheerio``` that probably don't export a global variable, how do we use this with importScripts? https://www.npmjs.com/package/cheerio

I have used WebWorkers on the front-end a few times, and the libraries I imported always exported a global variable, so I have no idea how to use importScripts that returns a variable - and I don't see how importScripts would work with NPM modules and module.exports, etc.

Can you advise on this? thanks! :)

**Comment by audreyt** [comment]
Browserify is the de facto solution:
https://www.reddit.com/r/node/comments/3avbnl/could_someone_help_me_to_browserify_the_cheerio/

If you get it working would you like to add a description to our README as a pull request? :-)

**Comment by ORESoftware** [comment]
hmmm, yeah I would be happy to do that but I don't think I will be figuring that out anytime soon TBH

**Comment by audreyt** [comment]
Did you try `importScripts` https://wzrd.in/standalone/cheerio@latest as the link above pointed to?

**Comment by ORESoftware** [comment]
thanks I will try that ;)
