### ISSUE TITLE
Returning an array from thread

### ISSUE THREAD

**Issue by dfcreative** [audreyt/node-webworker-threads#99]
Hi @audreyt!

I am trying to use webworker-threads within [nogl-shader-output](https://npmjs.org/package/nogl-shader-output), and I observe that returning an array from the shader is the most time-consuming operation. It takes about 400ms on my laptop to return an array of 300×300 items.
I guess it happens because things get stringified on return.

Is there a fast way to return big data from a thread?
Thank you.

**Comment by dfcreative** [comment]
I guess it is related with #18

**Comment by audreyt** [comment]
It is indeed #18. One possible solution is #59 which would fix the issue — any help in looking how to revive that WIP very welcome.
